### ISSUE TITLE
Antispam filter

### ISSUE THREAD

**Issue by halamix2** [PHP-Outburst/myUPB#30]
Current captcha is not protecting anymore as it should and we need replacement.
Basildon forum uses trick disallowing registering new account with comma in the localization (e.g. *city, country* )  
* We could use recaptcha but it requires API key for every forum which is not the best option if we would want to make simple and easy to use forum
* Maybe honeypot (hidden textfield visible only for bots) would help with some bots
* Timestamping - check how long registration took, don't register if it took too short
* IP/user-agent check

**Comment by phpcodex** [comment]
It would seem to me that the checking you propose could still be tricked, simply by using CURL, so we probably should either build a custom captcha with the GDLib, or alternatively, go down the API route as it would either be "on" or "off".

If we're going to spend time putting some checking in that we know can be bypassed, then we shouldn't bother with that, as we know we could hack it ourselves.

Once the Administrator has registered, we should have things like "secure your forum" notices if they have not registered for an API key/It's not working.

**Comment by blackcrack** [comment]
the new captcha "i be not a Robot" or the one with the 3 Pictures, "click the stores" or "klick the Roof's"
it's maybe not bad, but i write this only as suggestion and for speaking about.. it is they captcha depended of an google account ?  
By the way, the honeypot on the regestration did you see ?.. this is maybe also not bad, an entry who not be see via style but the robots / bots be clicking it yes or so.. and this is named as "Honeypott" where bot's fall in because they clicking yes or something.. and the human it is not see that ..

best regards
blacky

**Comment by halamix2** [comment]
Old discussion: http://www.basildon.com/upb/viewtopic.php?id=6&t_id=19

**Comment by blackcrack** [comment]
👍
