### ISSUE TITLE
Change session location for shared servers

### ISSUE THREAD

**Issue by halamix2** [PHP-Outburst/myUPB#40]
From http://www.basildon.com/upb/viewtopic.php?id=6&t_id=37 :  
We could add session_save_path() before session_start() for servers with no write permissions in default session folder.

**Comment by phpcodex** [comment]
If the user doesn't have access to set a session, this would then be a host issue. Every LAMP stack is setup in a way that all sessions are saved to a writable folder, so the fact a session is not saved would create greater worry. That being said, if we did change the path to a path of that inside the UPB folder, we could potentially take up more disk space on someones server needlessly.

It sounds like something else may be happening, further investigation required and replication due in order to act upon I would suggest.
