### ISSUE TITLE
The SKIN_DIR constant is undefined.

### ISSUE THREAD

**Issue by sarnobat** [PHP-Outburst/myUPB#59]
<img width="837" alt="screen shot 2017-08-28 at 6 00 49 pm" src="https://user-images.githubusercontent.com/2905777/29799823-390c70f0-8c1b-11e7-9192-2e60a724fcd2.png">

### What happened

I started getting an error that prevented me from accessing my forum (screenshot attached)

### Expected result

I should be able to see my forum.

### How to reproduce

* Go to: http://netgear.rohidekar.com/deleteme/index.php

### Additional info

It used to work. I don't think I changed anything. I also tried reinstalling but I got the same error.

**Comment by sarnobat** [comment]
Oh wait, I needed to chmod 777 everything AFTER the data dir was created. I think I'm fine now.

**Comment by halamix2** [comment]
I thought chmod 644 should be enough,777 is not good for security

**Comment by sarnobat** [comment]
Ooops, I'd misread the instructions from readme.txt :)

**Comment by blackcrack** [comment]
@Halamix2 @phpcodex 
by the way, i have see, the Apache create the DB, therefore should be/exist a kill-switch to be able
for apache to remove the db-folders. Maybe something like a popup for re-asking, do you want really remove the DB-folder and or also a "rm -rf ./" and "rm -rf $TextDB-folder" as Apache in the Administrator area/page, because if you upload the Forum by an ISP and the Apache create a own folder with db-entrys on a Internet Service Provider webspace, it is unable as Customer/User to delete the whole sub-folders where has create by Apache. For this should exist a possible for remove via apache the db-folder and the whole Forums-folder. (maybe you could make an new issue if it's worth ? )

best regards
Blacky
