### ISSUE TITLE
Suggested file mode too high (777)

### ISSUE THREAD

**Issue by halamix2** [PHP-Outburst/myUPB#60]
### What happened
Readme.txt says to chmod everything to 777, this is a security problem.

### Expected result

We should check if everything works with 644 

### To do
- [ ] check if UPB works witch chmod set to 644
    - [ ] clean install
    - [ ] already installed
- [ ] check if files created by the installer  have proper mode
    - [ ] config.php
    - [ ] data folder
    - [ ] upload folder
- [ ] change instructions in readme.txt
- [ ] check chmod during installation and warn user if set too high

**Comment by blackcrack** [comment]
it is possible to let check if a "ftp-user" exist and give them writingrights,
because by installation it is use the Apache-User or the user where the webserver runs,
because this , if you install the UPB over websurface, so, with the Webuser (apache/webuser/or what ever with the webrights from the provider) it is impossible to delete as FTP-User "@ the provider" as Paid user,
delete the full upb-folder because the tb and somt writing from the configfiles and so ..
i am not so good to know if it's works or not, to set writing rights to "ftpuser(if exist)"
or, by install the possible to setting up the userrights (pulldown-list of the groups of the System if it's works, reading out the groups from the system, make a list and chown the files and wringing of the files, like db.. )
just so an idea .. sometime have the Providers users like "ftpuser" as group or guided user
or something like i know..

best regards
Blacky
